package pims.config.dao;

import pims.config.DBConnection;
import java.sql.*;

public class ReportDAO {
    //shows every sale/transaction that was completed.
    public ResultSet getSalesReport() throws Exception {
        String sql = """
                SELECT s.sale_id, s.sale_date,s.total_amount,u.full_name AS cashier_name
                FROM sales s
                LEFT JOIN users u
                    ON s.user_id = u.user_id
                ORDER BY s.sale_date DESC
                """;
        Connection con = DBConnection.getConnection();
        PreparedStatement ps = con.prepareStatement(sql);

        return ps.executeQuery();
    }

    //shows how many units of each medicine have been sold and the total revenue generated by that medicine
    public ResultSet getItemWiseSalesReport() throws Exception {
        String sql = """
                SELECT m.medicine_id, m.name AS medicine_name, SUM(si.quantity_sold) AS total_quantity_sold, SUM(si.quantity_sold * si.price_at_sale)
                    AS total_sales_amount
                FROM sale_items si
                INNER JOIN medicines m
                    ON si.medicine_id = m.medicine_id
                GROUP BY m.medicine_id, m.name
                ORDER BY total_quantity_sold DESC
                """;
        Connection con = DBConnection.getConnection();
        PreparedStatement ps = con.prepareStatement(sql);

        return ps.executeQuery();
    }

    //shows medicine that are low on stock
    public ResultSet getLowStockReport() throws Exception {
        String sql = """
                SELECT medicine_id, name, company, quantity_in_stock, reorder_level
                FROM medicines
                WHERE quantity_in_stock <= reorder_level
                ORDER BY quantity_in_stock ASC
                """;
        Connection con = DBConnection.getConnection();
        PreparedStatement ps = con.prepareStatement(sql);

        return ps.executeQuery();
    }

    //shows medicine that expired
    public ResultSet getExpiryReport() throws Exception {
        String sql = """
                SELECT medicine_id, name,company, expiry_date, quantity_in_stock
                FROM medicines
                WHERE expiry_date <= DATE_ADD(CURDATE(), INTERVAL 1 MONTH)
                ORDER BY expiry_date ASC
                """;

        Connection con = DBConnection.getConnection();
        PreparedStatement ps = con.prepareStatement(sql);

        return ps.executeQuery();
    }
}